spring.application.name=account-service
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.structured.format.console=ecs
logging.structured.ecs.service.name=account-service
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always